# Site settings
title: OpenRocket Simulator
mantra: Build better rockets
email: openrocket-devel@lists.sourceforge.net 
description: > # this means to ignore newlines until "baseurl:"
  OpenRocket is a free, fully featured model rocket simulator that allows you to
  design and simulate your rockets before actually building and flying them.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://openrocket.info" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  openrocket 
current_version: 15.03
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
exclude: ['CNAME', 'Gruntfile.js', 'node_modules', 'original', 'resources', 'params.json', 'package.json']

# Build settings
markdown: kramdown
